In [2]:

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [18]:
# this program takes the train and test data from their files and puts them in arrays
# then for the train data, it creates word vectors stored in out.csv
# takes long to run, as there are over 40000 features per row
import csv
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
train_data = []
train_target = []
test_data = []
test_target = []

## replace path
with open('/content/drive/MyDrive/ColabNotebooks/subreddit-comments-dl-master/src/models/reddit_train.csv','rt')as f:
  all = csv.reader(f)
  for row in all:
    train_data.append(row[1])
    train_target.append(row[2])
  
with open('/content/drive/MyDrive/ColabNotebooks/subreddit-comments-dl-master/src/models/reddit_test.csv','rt')as f:
  all = csv.reader(f)
  for row in all:
    test_data.append(row[1])
    test_target.append(row[2])
# everything in 1 on, [1][0] = description. [1][1] = target

print(test_data[1])
print(train_target[2])
#print(allData[3099])

# do same for test data

# allTestData2 = []
# with open('testData.csv','rt')as f:
#   data = csv.reader(f)
#   for row in data:
#         allTestData2.append(row)
        
        
# everything in 1 on, [1][0] = description. [1][1] = target

#print(allTestData[1])
#print(allTestData[680])

# do same for test data

 The foster parents are pure wholesome and joy.

Was absolutely surprised by the appearance of the shazam family.

John glover still playing a dick father from his smallville days. That bullet immunity scene had me fucking rolling That cold shoulder from his mother was ICYYYY Something I really liked about the movie was the fact that they never explicitly said whether Billy was truly pure of heart. Having the 7 sins be freed before Billy meets Shazam was a good way to explain how a little shit like him could earn the power. 

And when he held the power of the 7 sins at the end and seemed unphased, you can take it as him finally becoming pure of heart or maybe the 7 sins having no effect on Shazam. It's a nice message that you don't have to be perfect to be a good person. When Freddy’s superhero self immediately started flying after his first transformation, I couldn’t help but think that the disabled version of himself always “believed” he could fly and that’s why he was able to fly so

In [19]:
import numpy as np, pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import GaussianNB
from sklearn.pipeline import make_pipeline
from sklearn.metrics import confusion_matrix, accuracy_score
sns.set() # use seaborn plotting style
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_validate
from sklearn.dummy import DummyClassifier
from sklearn import metrics




76278
76278
76278
61022
15256


In [22]:

import re 

def remove_emojis(data):
    emoj = re.compile("["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
        u"\U00002500-\U00002BEF"  # chinese char
        u"\U00002702-\U000027B0"
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        u"\U0001f926-\U0001f937"
        u"\U00010000-\U0010ffff"
        u"\u2640-\u2642" 
        u"\u2600-\u2B55"
        u"\u200d"
        u"\u23cf"
        u"\u23e9"
        u"\u231a"
        u"\ufe0f"  # dingbats
        u"\u3030"
                      "]+", re.UNICODE)
    return re.sub(emoj, '', data)


##preprocess data
preprocessed_train = []
for sentence in train_data[1:]:
    sentence=sentence.lower()
    #remove \n
    sentence = re.sub(r"\\n","", sentence)

    # removing links from text data
    sentence=re.sub('https?://[^\s<>"]+|www\.[^\s<>"]+',' ',sentence)
    
    #removing other symbols
    sentence=re.sub('[^0-9a-z]',' ',sentence)

    #removing extra white space
    sentence = " ".join(sentence.split())

    sentence = remove_emojis(sentence)
    preprocessed_train.append(sentence)

print(len(train_data))
print(len(preprocessed_train))

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(preprocessed_train)
final = X.toarray()
print(final)


2974
2974
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [43]:
import csv

# saving wordembeddings
with open("/content/drive/MyDrive/ColabNotebooks/subreddit-comments-dl-master/src/models/out_embedding.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(final)
    

In [42]:

# saving target of embeddings
with open("/content/drive/MyDrive/ColabNotebooks/subreddit-comments-dl-master/src/models/out_target.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(train_target[1:])

In [33]:
# this reads the data from csv and adds to a list, only for analysis
from csv import reader
list1 = []
with open('/content/drive/MyDrive/ColabNotebooks/subreddit-comments-dl-master/src/models/out.csv', 'r') as read_obj:
    csv_reader = reader(read_obj)
    for row in csv_reader:
        list1.append(row)

In [40]:
print(list1[0])
print(len(train_target[1:]))
print(len(final))

['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',