In [1]:
                # this program takes the train and test data from their files and puts them in arrays
# then for the train data, it creates word vectors stored in out.csv
# takes long to run, as there are over 40000 features per row

import csv
from sklearn.feature_extraction.text import CountVectorizer
allTrainData = []
with open('TD.csv','rt')as f:
  data = csv.reader(f)
  for row in data:
        allTrainData.append(row)
        
        
# everything in 1 on, [1][0] = description. [1][1] = target

#print(allData[1])
#print(allData[3099])

# do same for test data
        
# everything in 1 on, [1][0] = description. [1][1] = target

#print(allTestData[1])
#print(allTestData[680])

# do same for test data

In [2]:
import numpy as np, pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import GaussianNB
from sklearn.pipeline import make_pipeline
from sklearn.metrics import confusion_matrix, accuracy_score
sns.set() # use seaborn plotting style
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn import tree
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_validate
from sklearn.dummy import DummyClassifier
from sklearn import metrics




In [3]:
print(len(allTrainData))

3443


In [6]:
# train and target to boe the same size
# define the training set
train_data = []
train_target = []
test_data = []
test_target = []

for i in allTrainData[1:]:
    train_data.append(i[0])
    train_target.append(i[1])

    
  

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

temp = train_data

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(temp)
final = X.toarray()
print(final)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
import csv

# the first will be the title
with open("out.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerows(final)
    

In [49]:
# this reads the data from csv and adds to a list, only for analysis
from csv import reader
list1 = []
with open('out.csv', 'r') as read_obj:
    csv_reader = reader(read_obj)
    for row in csv_reader:
        list1.append(row)

In [10]:
print(len(train_data))

3442
